def gift_choice(status):
    match status:
        case "sinking":
            return "pictures/mirror/gifts/sinking.png"
        case "bleed":
            return "pictures/mirror/gifts/bleed.png"
        case "burn":
            return "pictures/mirror/gifts/burn.png"
        case "charge":
            return "pictures/mirror/gifts/charge.png"        
        case "poise":
            return "pictures/mirror/gifts/poise.png"
        case "rupture":
            return "pictures/mirror/gifts/rupture.png"
        case "tremor":
            return "pictures/mirror/gifts/tremor.png"
        case "slash":
            return "pictures/mirror/gifts/slash.png"
        case "pierce":
            return "pictures/mirror/gifts/pierce.png"
        case "blunt":
            return "pictures/mirror/gifts/blunt.png"
        case "random":
            return "pictures/mirror/gifts/random.png"
    
def squad_choice(status):
    match status:
        case "sinking":
            return "pictures/squads/sinking.png"
        case "bleed":
            return "pictures/squads/bleed.png"
        case "burn":
            return "pictures/squads/burn.png"
        case "charge":
            return "pictures/squads/charge.png"        
        case "poise":
            return "pictures/squads/poise.png"
        case "rupture":
            return "pictures/squads/rupture.png"
        case "tremor":
            return "pictures/squads/tremor.png"
        case "slash":
            return "pictures/squads/slash.png"
        case "pierce":
            return "pictures/squads/pierce.png"
        case "blunt":
            return "pictures/squads/blunt.png"     

def pack_choice(status):   
    match status:
        case "sinking":
            return "pictures/mirror/packs/status/sinking_pack.png"
        case "bleed":
            return "pictures/mirror/packs/status/bleed_pack.png"
        case "burn":
            return "pictures/mirror/packs/status/burn_pack.png"
        case "charge":
            return "pictures/mirror/packs/status/charge_pack.png"        
        case "poise":
            return "pictures/mirror/packs/status/poise_pack.png"
        case "rupture":
            return "pictures/mirror/packs/status/rupture_pack.png"
        case "tremor":
            return "pictures/mirror/packs/status/tremor_pack.png"
        case "slash":
            return "pictures/mirror/packs/status/slash_pack.png"
        case "pierce":
            return "pictures/mirror/packs/status/pierce_pack.png"
        case "blunt":
            return "pictures/mirror/packs/status/blunt_pack.png"
        
def enhance_gift_choice(status):
    match status:
        case "sinking":
            return "pictures/mirror/reststop/sinking_enhance.png"
        case "bleed":
            return "pictures/mirror/reststop/bleed_enhance.png"
        case "burn":
            return "pictures/mirror/reststop/burn_enhance.png"
        case "charge":
            return "pictures/mirror/reststop/charge_enhance.png"        
        case "poise":
            return "pictures/mirror/reststop/poise_enhance.png"
        case "rupture":
            return "pictures/mirror/reststop/rupture_enhance.png"
        case "tremor":
            return "pictures/mirror/reststop/tremor_enhance.png"
        case "slash":
            return "pictures/mirror/reststop/slash_enhance.png"
        case "pierce":
            return "pictures/mirror/reststop/pierce_enhance.png"
        case "blunt":
            return "pictures/mirror/reststop/blunt_enhance.png"
        
def reward_choice(status):
    match status:
        case "sinking":
            return "pictures/mirror/rewards/sinking_reward.png"
        case "bleed":
            return "pictures/mirror/rewards/bleed_reward.png"
        case "burn":
            return "pictures/mirror/rewards/burn_reward.png"
        case "charge":
            return "pictures/mirror/rewards/charge_reward.png"        
        case "poise":
            return "pictures/mirror/rewards/poise_reward.png"
        case "rupture":
            return "pictures/mirror/rewards/rupture_reward.png"
        case "tremor":
            return "pictures/mirror/rewards/tremor_reward.png"
        case "slash":
            return "pictures/mirror/rewards/slash_reward.png"
        case "pierce":
            return "pictures/mirror/rewards/pierce_reward.png"
        case "blunt":
            return "pictures/mirror/rewards/blunt_reward.png"